### PR TITLE
[Merged by Bors] - Updating Tests to new Hive version

### PR DESCRIPTION
**Pull request by Maleware**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
LGTM. Ci test: https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hive-operator-it-custom/4/console

**Comment by sbernauer** [comment]
Can you please add an CHANGELOG.md entry like "Add support for Hive 3.1.3"?

**Comment by Maleware** [comment]
> Can you please add an CHANGELOG.md entry like "Add support for Hive 3.1.3"?

Done

**Review by sbernauer — APPROVED** [review]
CI tests passed

**Pull request closed without merging**
