### PR TITLE
chore: bump stackable-operator version and fix minio installation command

### PR DESCRIPTION
**Pull request by xeniape**
# Description

When running the minio installation command, the following error is thrown:
```
helm install minio \
--version 4.0.2 \
--namespace default \
--set mode=standalone \
--set replicas=1 \
--set persistence.enabled=false \
--set buckets[0].name=hive,buckets[0].policy=none \
--set users[0].accessKey=hive,users[0].secretKey=hivehive,users[0].policy=readwrite \
--set resources.requests.memory=1Gi \
--set service.type=NodePort,service.nodePort=null \
--set consoleService.type=NodePort,consoleService.nodePort=null \
--repo https://charts.min.io/ minio
zsh: no matches found: buckets[0].name=hive,buckets[0].policy=none
```
This PR adds double quotes to the two settings throwing this error, which fixes it.

Edit: Also bumped `stackable-operator` version as part of this PR due to `cargo deny` errors.

### CODE REVIEW

**Review by sbernauer — DISMISSED** [review]
Thanks!
Not on my computer, but maybe this is a zsh vs bash thing

**Comment by sbernauer** [comment]
Please feel free to run `cargo update`

**Review by sbernauer — APPROVED** [review]

**Comment by sbernauer** [comment]
Btw, the command already worked in bash, but not zsh ;)

**Comment by xeniape** [comment]
> Btw, the command already worked in bash, but not zsh ;)

Yes, tried the updated command with bash to make sure it didn't break there after the change.

**Pull request merged**
